# Generated by Django 5.0 on 2024-01-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="title",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
